"""Parameters for the network DNA methylation clock pipeline.

All thresholds reproduce the published pipeline. This file is deliberately free of
machine-specific paths: the only directory it uses is a `synthetic_data/` folder next
to this file, created on demand for the synthetic smoke test (see `analysis.synth`).
To run on real data, load your own matrix and sample sheet directly with
`analysis.io_utils.load_methylation(beta_path, sheet_path)` — see the README Data section.
"""
from __future__ import annotations
import os
from pathlib import Path

SEED = 42

# ── Age-CpG selection / network / module parameters (published values) ──────────
RHO_THRESHOLD = 0.35        # |Spearman rho| CpG-vs-age cutoff                 (step 1)
TAU_THRESHOLD = 0.70        # |Spearman corr| edge cutoff for the network     (step 2)
INFOMAP_ARGS  = "--two-level --silent --seed 42"   # Infomap module detection (step 3)
K_PCS_DEFAULT = 60          # principal components in the Module-PCA clock     (step 4)
N_OUTER_FOLDS = 5           # outer folds for nested cross-validation

# ── Reference clocks used for benchmarking (via pyaging) ────────────────────────
REFERENCE_CLOCKS = ["horvath2013", "hannum", "altumage", "skinandblood", "han"]
CLOCK_LABELS = {
    "horvath2013": "Horvath", "hannum": "Hannum", "altumage": "AltumAge",
    "skinandblood": "Skin & Blood", "han": "Han",
}

# ── Synthetic smoke-test data (no downloads) ────────────────────────────────────
# Set EPICLOCK_SYNTHETIC=1 to route the pipeline at fictional data generated by
# analysis.synth.ensure_synthetic(). For real data, ignore this and pass explicit
# paths to io_utils.load_methylation().
USE_SYNTHETIC = os.environ.get("EPICLOCK_SYNTHETIC", "0") == "1"
SYNTH_DIR = Path(__file__).resolve().parent / "synthetic_data"
SYNTH_DIR.mkdir(parents=True, exist_ok=True)   # under the package dir; always writable
